import AppKit
import SwiftUI
import XCTest

@testable import Kohai

/// Renders every preview state (see `PreviewCatalog.all`) to a PNG in
/// `design-snapshots/` at the package root, so the design can be reviewed
/// without opening Xcode. Override the folder with KOHAI_SNAPSHOT_DIR.
@MainActor
final class SnapshotTests: XCTestCase {

    func testRenderEveryPreviewStateToPNG() throws {
        let dir = Self.outputDirectory()
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        var index = "# Kohai design snapshots\n\nGenerated by `SnapshotTests`. @2x PNGs.\n\n"

        for entry in PreviewCatalog.all {
            let renderer = ImageRenderer(content: entry.make(true))
            renderer.scale = 2

            guard let cgImage = renderer.cgImage else {
                XCTFail("ImageRenderer produced no image for \(entry.id)")
                continue
            }
            let rep = NSBitmapImageRep(cgImage: cgImage)
            guard let png = rep.representation(using: .png, properties: [:]) else {
                XCTFail("PNG encoding failed for \(entry.id)")
                continue
            }
            XCTAssertGreaterThan(png.count, 1_000, "\(entry.id) looks blank")
            try png.write(to: dir.appendingPathComponent("\(entry.id).png"))
            index += "- `\(entry.id).png`: \(entry.title)\n"
        }

        try index.write(
            to: dir.appendingPathComponent("INDEX.md"), atomically: true, encoding: .utf8)
    }

    /// The template NSImage for the status item must exist and be a template.
    func testMenuBarTemplateImagesAreTemplates() {
        for filled in [false, true] {
            let image = MenuBarIconImage.make(filled: filled)
            XCTAssertNotNil(image)
            XCTAssertEqual(image?.isTemplate, true)
        }
    }

    static func outputDirectory() -> URL {
        if let override = ProcessInfo.processInfo.environment["KOHAI_SNAPSHOT_DIR"] {
            return URL(fileURLWithPath: override, isDirectory: true)
        }
        // Tests/KohaiTests/SnapshotTests.swift -> package root
        return URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("design-snapshots", isDirectory: true)
    }
}
